StarTech/IPGMMS/IPGMMS/Controllers/MemberController.cs
using IPGMMS.Abstract;
using IPGMMS.Models;
using IPGMMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace IPGMMS.Controllers
{
    public class MemberController : MController
    {
        private IMemberRepository memberRepo;
        private IContactRepository contactRepo;

        public MemberController(IMemberRepository repo, IContactRepository cRepo)
        {
            memberRepo = repo;
            contactRepo = cRepo;
        }

        /// <summary>
        /// GET: Members
        /// Displays all members sorted by last name, 3 at a time on a page with paging.
        /// </summary>
        /// <param name="page">The page number</param>
        /// <returns></returns>
        public ActionResult Index(int? page)
        {
            var members = memberRepo.GetAllMembers;

            int pageSize = 3;
            double pages = Math.Ceiling((double)members.Count() / pageSize);

            int pageNum = page ?? 1;

            ViewBag.Pages = pages;

            var membersPaged = members.Skip(pageSize * (pageNum - 1)).Take(pageSize).ToList();

            return View(membersPaged);
        }

        /// <summary>
        /// GET: Details
        /// Displays a member's details based on the membership level of the
        /// member. This will only send select information to the view to
        /// prevent private information from being displayed.
        /// 
        /// Defaults to ID = 5 for some reason.
        /// </summary>
        /// <param name="ID"> The member ID to display</param>
        /// <returns></returns>
        public ActionResult Details(int? ID)
        {
            if (!ID.HasValue)
            {
                ID = 5;
            }

            Member memb;
            memb = memberRepo.Find(ID);
            if (memb == null)
            {
                ID = 5;
                memb = memberRepo.Find(5);
            }
            ContactInfo cont = new ContactInfo();

            // This should probably be checked in the repo method rather
            // than here, but such is life.
            try
            {
                cont = contactRepo.ListingInfoFromMID(ID);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.StackTrace);
            }

            MemberDetails memDet = new MemberDetails();
            memDet.Contact = cont;

            memDet.MemberLevelbyInt = memb.MemberLevel;
            string abbr;
            ToAbbr.TryGetValue(memb.MemberLevel1.MLevel, out abbr);
            memDet.LevelAbbrev = ", " + abbr;
            memDet.FullName = memb.FullName;
            memDet.BusinessName = memb.BusinessName;
            if (memb.MemberLevel > 1)
            {
                memDet.MemberLevel = memb.MemberLevel1.MLevel;
                memDet.Website = memb.Website;
            }
            else
            {
                // We have no schools set in database. Maybe require students
                // to list their school as the business name.
                memDet.BusinessName = "Grooming School";
            }
            if (cont.StateName != null)
            {
                memDet.Location = cont.StateName + ", " + cont.Country;
            }
            

            return View(memDet);
        }

        /// <summary>
        /// GET: Member Create
        /// This is the GET for the application form for a user to provide thier basic information in order to apply to become an IPG member.
        /// This from requires the user to have already registered on the website.
        /// </summary>
        /// <returns>A View object for the Member/Apply page or a redirect to their details page if already a member</returns>
        [Authorize]
        //[ValidateAntiForgeryToken]
        public ActionResult Apply()
        {
            var userID = User.Identity.GetUserId();
            if (memberRepo.FindByIdentityID(userID) == null) // current Identity user doesn't already have an associated IPG account/application
            {
                MemberInfoViewModel newMember = new MemberInfoViewModel();
                newMember.MemberInfo = memberRepo.CreateMember();
                //autopopulate the user's email, member level, and identity ID
                newMember.MailingInfo = contactRepo.CreateContact();
                newMember.MailingInfo.Email = UserManager.GetEmail(userID);
                newMember.MemberInfo.MemberLevel = memberRepo.GetMemberLevelID("Uncategorized");
                newMember.MemberInfo.Identity_ID = userID;
                return View(newMember);
            }
            else // current Identity user has already applied or is already an IPG member
            {
                return RedirectToAction("Index", "Manage");
            }
        }

        /// <summary>
        /// POST: Member Create
        /// The post method for the application form for a user that is applying to become and IPG member
        /// </summary>
        /// <param name="newMember">The viewmodel containing the information provided by the applying user</param>
        /// <returns>A redirect view object to the user's details page if successful, otherwise a view object
        /// back to the application form</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Apply(MemberInfoViewModel newMember)
        {
            if (ModelState.IsValid)
            {
                Member memb = newMember.MemberInfo;
                ContactInfo mail = newMember.MailingInfo;
                ContactInfo list = newMember.ListingInfo;
                // set signup date to today and generate member number
                memb.Membership_SignupDate = DateTime.Today;
                memb.Membership_Number = memberRepo.setMemberNumber(memb, mail);
                // insert member and mailingInfo and link the two
                memb = memberRepo.InsertorUpdate(memb);
                mail = contactRepo.InsertorUpdate(mail);
                contactRepo.LinkMailingContact(memb, mail);
                // insert listingInfo and link to member
                list = contactRepo.InsertorUpdate(list);
                contactRepo.LinkListingContact(memb, list);

                return RedirectToAction("Index", "Manage", new { success = true });
            }

            return View(newMember);
        }

        Dictionary<String, String> ToAbbr = new Dictionary<string, string>()
        {
            {"Student Member", "Student" },
            {"IPG Member", "IPG Member" },
            {"Certified Professional Groomer", "CPG" },
            {"Certified Advanced Professional Groomer", "APG" },
            {"International Certified Master Groomer", "ICMG" },
            {"Approved Salon", "Salon" },
            {"Approved School", "School" },
            {"Member School", "School" },
            {"Uncategorized", "Newbie" }
        };
    }
}

StarTech/IPGMMS/IPGMMS/Views/Shared/_AdminNav.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="navbar navbar-fixed-left">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">
            <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
        </a>
    </div>
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Members</a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    @Ajax.ActionLink(
                    "View",
                    "ListMembers",
                    "Portal",
                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "CenterPartialUpdateFrame"
                    })
                </li>
                <li>
                    @Ajax.ActionLink(
                   "Add",
                   "AddMember",
                   "Portal",
                   new AjaxOptions
                   {
                       HttpMethod = "GET",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "CenterPartialUpdateFrame"
                   })
                </li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tests</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Certifications</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Test Results</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">View</a></li>
                <li><a href="#">Add</a></li>
                <li><a href="#">Update</a></li>
            </ul>
        </li>
    </ul>
</div>

StarTech/IPGMMS/IPGMMS/Views/Shared/_AdminPortalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - IPG Admin Portal</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/AdminPortalSharedLayout.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="w3-white">

    <!--Top Nav Bar-->
    <div class="w3-navbar w3-black w3-hide-small">
        @Html.Partial("_LoginPartial")
    </div>
    <!-- Icon Bar (Sidebar - hidden on small screens) -->
    <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center w3-black">
        <div style="width:100%"><a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/IPGLogo.jpg" alt="Top Logo" /></a></div>
        <div class="dropdown">
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
                <i class="fa fa-user w3-xxlarge"></i>
                <p>MEMBERS</p>
            </a>
            <div class="dropdown-content">
                <a href="@Url.Action("AddMember", "Portal")">Add Member</a>
                <a href="@Url.Action("UpdateMember","Portal")">Update Member</a>
                <a href="@Url.Action("ListMembers","Portal")">Search Members</a>
            </div>
        </div>
        <div class="dropdown">
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
                <i class="fa fa-clipboard w3-xxlarge"></i>
                <p>RESULTS</p>
            </a>
            <div class="dropdown-content">
                <a href="#">TO BE ADDED</a>
                <a href="#">TO BE ADDED</a>
            </div>
        </div>
        <div class="dropdown">
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
                <i class="fa fa-list-alt w3-xxlarge"></i>
                <p>TEST CERT</p>
            </a>
            <div class="dropdown-content">
                <a href="#">TO BE ADDED</a>
                <a href="#">TO BE ADDED</a>
            </div>
        </div>
        <div class="dropdown">
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
                <i class="fa fa-file w3-xxlarge"></i>
                <p>REPORTS</p>
            </a>
            <div class="dropdown-content">
                <a href="#">TO BE ADDED</a>
                <a href="#">TO BE ADDED</a>
            </div>
        </div>
    </nav>

    <!-- Navbar on small screens (Hidden on medium and large screens) -->
    <div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
        <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
            <a href="#" class="w3-bar-item w3-button" style="width:20% !important">MEMBERS</a>
            <a href="#" class="w3-bar-item w3-button" style="width:20% !important">TEST RESULTS</a>
            <a href="#" class="w3-bar-item w3-button" style="width:20% !important">TEST CERT</a>
            <a href="#" class="w3-bar-item w3-button" style="width:20% !important">REPORTS</a>
            <a href="javascript:document.getElementById('logoutForm').submit()" class="w3-bar-item w3-button" style="width:20% !important">LOG OFF</a>
        </div>
    </div>

    <!-- END PAGE CONTENT -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- Page Content -->
    <div class="w3-padding-medium" id="main">
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge" id="mainFooter">
        <p class="w3-medium">Powered by StarTech</p>
        <!-- End footer -->
    </footer>



</body>

</html>

StarTech/IPGMMS/IPGMMS/Views/Shared/_GoogleMap.cshtml
@model IPGMMS.ViewModels.MemberDetails

<!--This is the partial view that renders a Google map based on the mapURL string that is in the ContactInfo.Meta
    partial class. Will render a view of the world if there is no information for the address of the groomer.-->

<div class="row col-md-12">
    <iframe width="450" height="250" frameborder="0" style="border:0" src="@Url.Content(Model.Contact.mapURL)" )></iframe>
</div>

StarTech/IPGMMS/IPGMMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IPGMMS</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/SharedLayout.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="w3-content" style="max-width:100%">

    <!-- Sidebar (hidden by default) -->
    <nav class="w3-sidebar w3-bar-block w3-card-2 w3-top w3-xlarge w3-animate-left w3-light-gray" style="display:none;z-index:2;width:40%;max-width:300px" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button"><i class="fa fa-close"></i></a>
        <div class="w3-padding-12"><a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/IPGLogo2.png" /></a></div>
        <a href="@Url.Action("Index","Member")" onclick="w3_close()" class="w3-bar-item w3-button">IPG Member Search</a>
        <a href="#" onclick="w3_close()" class="w3-bar-item w3-button">About IPG Membership</a>
       
    </nav>

    <!-- Top menu -->
    <div class="w3-top w3-light-gray w3-padding-right">
        <div class="w3-xlarge" style="max-width:100%; margin:auto">
            <div class="w3-button w3-left" onclick="w3_open()"><i class="fa fa-bars w3-xxlarge"></i></div>
            <div class="w3-right">@Html.Partial("_LoginPartial")</div>
            <div class="w3-left"><h4 class="w3-hide-small">International Professional Groomers, Inc.</h4></div>
        </div>
    </div>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- Page Content -->
    <div class="w3-padding-large" id="main">
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

        <!-- Footer -->
        <footer class="w3-container w3-padding-32 w3-dark-grey">
            <div class="w3-row-padding">
                <div class="w3-quarter w3-left">          
                        <h5><a href="@Url.Action("Index","Home")">Home</a></h5>
                        <h5><a href="@Url.Action("About","Home")">About IPG</a></h5>
                        <h5><a href="@Url.Action("FAQ", "Home")">FAQ</a></h5>
                        <h5><a href="@Url.Action("Contact", "Home")">Contact IPG</a></h5>
                    </div>
                    <div class="w3-quarter">
                        <h5>IPG Certification Tracks</h5>
                        <h5>IPG Events</h5>
                        <h5>IPG Products</h5>
                    </div>
                <div class="w3-half">
                    <img src="~/Content/Images/IPGLogo.jpg">
                </div>
                </div>
        </footer>



    <!-- END PAGE CONTENT -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/SharedLayout.js")
    @RenderSection("scripts", required: false)

    <script type="text/javascript" src="HomePage.js"></script>
</body>

</html>

StarTech/IPGMMS/IPGMMS/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IPGMMS</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/w3.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            @*<div class="row col-md-3">
                    <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
                </div>
                <h1 class="row col-md-9">International Professional Groomers, Inc<br /><small>Member Management System</small></h1>*@
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IPGMMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("IPG Members", "Index", "Member")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <hr />
        <p>&copy; @DateTime.Now.Year - StarTech Application</p>
        <img src="~/Content/Images/IPGLogo.jpg" alt="Bottom Logo" />
    </footer>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StarTech/IPGMMS/IPGMMS/Views/Shared/_LeftNav.cshtml
@{
    ViewBag.Title = "Home Page";
}


<br>
<br>

<link href="@Url.Content("~/Content/Homepage.css")" rel="stylesheet" type="text/css" />

<div class="left-navbar">
    <div class="topLogo">
        <img src="~/Content/Images/IPGLogo2.jpeg" alt="Top Logo" />
    </div>
    <p>
        Links go here, these not in order. Will need to touch up once links are established.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About IPG", "About", "Home")</li>
        <li>@Html.ActionLink("Contact IPG", "Contact", "Home")</li>
        <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
        <li>@Html.ActionLink("Members", "Index", "Member")</li>
        <li>@Html.ActionLink("Admin", "Index", "Portal")</li>
        <li>Yupe, you guessed it.</li>
        <li>Another one</li>
        <li>And another</li>
        <li>And another</li>
        <li>Hi</li>
    </ul>
</div>