StarTech/IPGMMS/IPGMMS/Controllers/PortalController.cs
using IPGMMS.Abstract;
using IPGMMS.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Diagnostics;
using IPGMMS.ViewModels;

namespace IPGMMS.Controllers
{
    [AdminAuthorize(Roles = "Admin")]
    public class PortalController : MController
    {
        private IMemberRepository memberRepo;
        private IContactRepository contactRepo;

        public PortalController(IMemberRepository mRepo, IContactRepository cRepo)
        {
            memberRepo = mRepo;
            contactRepo = cRepo;
        }

        //***********************************************ADMIN PORTAL INDEX*****************************
        // GET: Portal
        public ActionResult Index()
        {
            var user = User.Identity;
            ViewBag.Name = user.Name;

            return View();
        }

        //***********************************************LIST MEMBER INFO*****************************
        public ActionResult ListMembers(int? page, string sortOrder, string searchString)
        {

            var members = memberRepo.GetAllMembers;

            //This section is to check the search string and return a member list that
            //has only the information that was searched for 
            //Credit for filtering and some paging code goes to: 
            //docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application
            if (!String.IsNullOrEmpty(searchString))
            {
                members = members.Where(s => s.LastName.ToLower().Contains(searchString.ToLower())
                                       || s.FirstName.ToLower().Contains(searchString.ToLower()));
            }

            // It will switch the stored variable so it will use the other
            // next time.
            ViewBag.lName = String.IsNullOrEmpty(sortOrder) ? "l_name" : "";
            ViewBag.mem_num = sortOrder == "mem_num" ? "num_desc" : "mem_num";
            ViewBag.date_start = sortOrder == "date_start" ? "start_desc" : "date_start";
            ViewBag.date_end = sortOrder == "date_end" ? "end_desc" : "date_end";
            ViewBag.f_name = sortOrder == "f_name" ? "fname_desc" : "f_name";
            ViewBag.b_name = sortOrder == "b_name" ? "bname_desc" : "b_name";
            ViewBag.mem_lvl = sortOrder == "mem_lvl" ? "lvl_desc" : "mem_lvl";

            // Initialize the variable that will become the sort option
            Func<Member, object> sorting;

            // Check each of the four dictionaries for sort params
            // Dictionary is at the bottom of file
            if (!String.IsNullOrEmpty(sortOrder))
            {
                if (sortBy.TryGetValue(sortOrder, out sorting))
                {
                    members = members.OrderBy(sorting);
                }
                else if (sortByDesc.TryGetValue(sortOrder, out sorting))
                {
                    members = members.OrderByDescending(sorting);
                }
                else // Shouldn't need this but will catch any non-match
                {
                    members = members.OrderByDescending(m => m.LastName);
                }
            }
            else // Catch if sortOrder is null or empty
            {
                members = members.OrderByDescending(m => m.LastName);
            }

            int pageSize = 5; //the number of items that can appear on each page.
            int startPage = (page ?? 1);

            return View("ListMembers", members.ToList().ToPagedList(startPage, pageSize));
        }

        //***********************************************DETAILED MEMBER INFO*****************************
        public ActionResult DetailMember()
        {
            return View("DetailMember");
        }

        //***********************************************ADD MEMBER***************************************
        // GET: Addmember()
        public ActionResult AddMember()
        {
            MemberCreate createMember = new MemberCreate();
            createMember.Levels = memberRepo.GetLevels;
            return View("AddMember", createMember);
        }

        // POST: AddMember()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMember(MemberCreate infos)
        {

            if (ModelState.IsValid)
            {
                Member memb = infos.MemberInfo;
                ContactInfo mail = (ContactInfo)infos.MailingInfo;
                memb.Membership_Number = memberRepo.setMemberNumber(memb, mail);
                memb = memberRepo.InsertorUpdate(memb);
                // Mailing info is required.
                mail = contactRepo.InsertorUpdate(mail);
                contactRepo.LinkMailingContact(memb, mail);

                // Listing info is optional.
                ContactInfo list = infos.ListingInfo;
                list = contactRepo.InsertorUpdate(list);
                contactRepo.LinkListingContact(memb, list);

                Debug.WriteLine("Says it's valid but not really, maybe");
                return RedirectToAction("UpdateMember", new { id = memb.ID });
                //return View("DetailMember", memb);
            }
            infos.Levels = memberRepo.GetLevels;
            return View("AddMember", infos);
        }

        public ActionResult UpdateMember(int? id)
        {
            if (id == null)
            {
                id = 4;
            }
            MemberInfoViewModel info = new MemberInfoViewModel();
            info.MemberInfo = memberRepo.Find(id);
            //Try to get the Listing info from the contact repo. If there's no listing 
            //for this member, then the info.ListingInfo is set to null for this
            //ViewModel that is passed back to the view.
            try
            {
                info.ListingInfo = contactRepo.ListingInfoFromMID(id);
            }
            catch(System.InvalidOperationException)
            {
                info.ListingInfo = null;
            }
            //Try to get the Mailing info from the contact repo. If there's no listing 
            //for this member, then the info.MailingInfo is set to null for this
            //ViewModel that is passed back to the view.
            try
            {
                info.MailingInfo = contactRepo.MailingInfoFromMID(id);
            }
            catch (System.InvalidOperationException)
            {
                info.MailingInfo = null;
            }

            return View(info);
        }

        //***********************************************UPDATE MEMBER INFO*****************************
        /// <summary>
        /// This method is the GET for UpdateMemberInfo(). This takes in the memberID 
        /// (not to be confused with the memberNumber) and, if a valid memberID, returns
        /// a form that allows the user to update member information.
        /// </summary>
        /// <param name="memID"></param>
        /// <returns>The UpdateMemberInfo view. </returns>
        public ActionResult UpdateMemberInfo(int? memID)
        {
            if (memID == null)
            {
                return View(Request.UrlReferrer.ToString());
            }
            if (memberRepo.Find(memID) == null)
            {
                return View(Request.UrlReferrer.ToString());
            }

            MemberInfoVM memberinfo = new MemberInfoVM();
            memberinfo.Levels = memberRepo.GetLevels;
            memberinfo.MemberInfo = memberRepo.Find(memID);

            return View(memberinfo);
        }

        /// <summary>
        /// This method is the POST for UpdateMemberInfo(). This takes in a ViewModel parameter
        /// that holds a member object and a select list of membership levels. This method will
        /// save updates to the database and return the user to the UpdateMember page to view 
        /// their changes.
        /// </summary>
        /// <param name="memb"></param>
        /// <returns>If the model state is valid, this returns the user back to the UpdateMember view
        /// if it is not valid, it returns the user to the UpdateMemberInfo view with the ViewModel given.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMemberInfo(MemberInfoVM memb)
        {
            if (ModelState.IsValid)
            {
                var member = memb.MemberInfo;
                memberRepo.InsertorUpdate(member);
                MemberInfoViewModel memberDetails = new MemberInfoViewModel();
                memberDetails.MemberInfo = member;
                memberDetails.ListingInfo = contactRepo.ListingInfoFromMID(member.ID);
                memberDetails.MailingInfo = contactRepo.MailingInfoFromMID(member.ID);
                memb.Levels = memberRepo.GetLevels;
                return View("UpdateMember", memberDetails);
            }

            memb.Levels = memberRepo.GetLevels;
            return View(memb);
        }

        // GET: UpdateMemberMailing()
        public ActionResult UpdateMemberMailing(int? memID)
        {
            
            if (memID == null)
            {
                return View("Index");
                //return View(Request.UrlReferrer.ToString());
            }
            

            return View(contactRepo.MailingInfoFromMID(memID));
        }

        // POST: UpdateMemberMailing()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMemberMailing(ContactInfo info)
        {
            if (ModelState.IsValid)
            {
                contactRepo.InsertorUpdate(info);
                MemberInfoViewModel memberDetails = new MemberInfoViewModel();
                var memID = contactRepo.getMemberID(info);

StarTech/IPGMMS/IPGMMS/Views/Portal/AJAXListMembers.cshtml
@model PagedList.IPagedList<IPGMMS.Models.Member>
@using PagedList.Mvc

@{
    ViewBag.Title = "List Members";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using (Ajax.BeginForm("ListMembers", "Portal", FormMethod.Post,
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        InsertionMode = InsertionMode.Replace,
                                        UpdateTargetId = "CenterPartialUpdateFrame"
                                    }))
{
<p>
    Find by name: @Html.TextBox("SearchString")
    <input type="submit" value="Search" />
</p>
}

<table class="table">
    <tr>
        <th>
            @{ var memlvl = @Html.DisplayNameFor(model => model.FirstOrDefault().MemberLevel1.MLevel).ToString();}
            @Ajax.ActionLink(
            memlvl,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.mem_lvl },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var userName = @Html.DisplayNameFor(model => model.FirstOrDefault().UserName).ToString();}
            @Html.ActionLink(userName,"ListMembers","Portal", new { sortOrder = ViewBag.userName}, null)
            @*@Ajax.ActionLink(
            userName,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.userName },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })*@

        </th>
        <th>
            @{ var mem_num = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_Number).ToString();}
            @Ajax.ActionLink(
            mem_num,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.mem_num },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var date_start = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_SignupDate).ToString();}
            @Ajax.ActionLink(
            date_start,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.date_start },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var date_end = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_ExpirationDate).ToString();}
            @Ajax.ActionLink(
            date_end,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.date_end },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var f_name = @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName).ToString();}
            @Ajax.ActionLink(
            f_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.f_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var m_name = @Html.DisplayNameFor(model => model.FirstOrDefault().MiddleName).ToString();}
            @Ajax.ActionLink(
            m_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.m_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var l_name = @Html.DisplayNameFor(model => model.FirstOrDefault().LastName).ToString();}
            @Ajax.ActionLink(
            l_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.lName },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var b_name = @Html.DisplayNameFor(model => model.FirstOrDefault().BusinessName).ToString();}
            @Ajax.ActionLink(
            b_name,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.b_name },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th>
            @{ var website = @Html.DisplayNameFor(model => model.FirstOrDefault().Website).ToString();}
            @Ajax.ActionLink(
            website,
            "ListMembers",
            "Portal",
            new { sortOrder = ViewBag.website },
            new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "CenterPartialUpdateFrame",
            })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_SignupDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>
<div>
    Page @(Model.PageNumber < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("ListMembers", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.currentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
        new AjaxOptions() { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "CenterPartialUpdateFrame" }))
</div>

StarTech/IPGMMS/IPGMMS/Views/Portal/AddCertification.cshtml
@{
    ViewBag.Title = "AddCertification";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>AddCertification</h2>
<p>Here we will allow an admin to create a new certification</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/AddTest.cshtml
@{
    ViewBag.Title = "AddTest";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>AddTest</h2>
<p>Here we will allow the admin to add a new test.</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/DetailCertification.cshtml
@{
    ViewBag.Title = "DetailCertification";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>DetailCertification</h2>
<p>Give the details of the certification, notes, and tests associated.</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/DetailMember.cshtml
@model IPGMMS.Models.Member

@{
    ViewBag.Title = "ListTests";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MemberLevel1.MLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberLevel1.MLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Membership_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Membership_SignupDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership_SignupDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Membership_ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership_ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/Index.cshtml
@{
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
    ViewBag.Title = "Index";
}

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

@section scripts {
    <link href="@Url.Content("~/Content/Homepage.css")" rel="stylesheet" type="text/css" />
}

<!--
@*<div class="col-md-2">*@
@Html.Partial("_AdminNav")
@*</div>*@-->

@*<div class="col-md-10">*@
<div class="container">
    <div class="row">
        <br />
        <br />
        <p>
            This will be the Admin Portal showing all sorts of neat stuff.
            @*@if (ViewBag.displayAdmin == "Yes")
                {*@
            <h1> Welcome @User.Identity.Name</h1>
        <p>
            This page will be worked on in due time. For now just sit back and enjoy the blue along the top and left side.
            This is a test @User.Identity.AuthenticationType
        </p>

        @*}
            else
            {

                <h2>Hey wait <strong>@ViewBag.Name!</strong> You're not an Admin!!</h2>
            }
            </p>*@
<!--
        <div id="CenterPartialUpdateFrame"></div>
    </div>
</div>-->
 </div>
</div>

StarTech/IPGMMS/IPGMMS/Views/Portal/ListCertifications.cshtml
@{
    ViewBag.Title = "ListCertifications";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>ListCertifications</h2>
<p>Here we will list all the current certifications.</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/ListMembers.cshtml
@model PagedList.IPagedList<IPGMMS.Models.Member>
@using PagedList.Mvc

@{
    ViewBag.Title = "List Members";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table" id="memberListTable">
    <tr>
        <th>
            @{ var mem_num = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_Number).ToString();}
            @Html.ActionLink(mem_num, "ListMembers", "Portal", new { sortOrder = ViewBag.mem_num }, null)
        </th>
        <th>
            @{ var date_start = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_SignupDate).ToString();}
            @Html.ActionLink(date_start, "ListMembers", "Portal", new { sortOrder = ViewBag.date_start }, null)
        </th>
        <th>
            @{ var date_end = @Html.DisplayNameFor(model => model.FirstOrDefault().Membership_ExpirationDate).ToString();}
            @Html.ActionLink(date_end, "ListMembers", "Portal", new { sortOrder = ViewBag.date_end }, null)
        </th>
        <th>
            @{ var f_name = @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName).ToString();}
            @Html.ActionLink(f_name, "ListMembers", "Portal", new { sortOrder = ViewBag.f_name }, null)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MiddleName)
        </th>
        <th>
            @{ var l_name = @Html.DisplayNameFor(model => model.FirstOrDefault().LastName).ToString();}
            @Html.ActionLink(l_name, "ListMembers", "Portal", new { sortOrder = ViewBag.l_name }, null)
        </th>
        <th>
            @{ var b_name = @Html.DisplayNameFor(model => model.FirstOrDefault().BusinessName).ToString();}
            @Html.ActionLink(b_name, "ListMembers", "Portal", new { sortOrder = ViewBag.b_name }, null)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Website)
        </th>
        <th>
            @{ var memlvl = @Html.DisplayNameFor(model => model.FirstOrDefault().MemberLevel1.MLevel).ToString();}
            @Html.ActionLink(memlvl, "ListMembers", "Portal", new { sortOrder = ViewBag.mem_lvl }, null)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_SignupDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Membership_ExpirationDate)
            </td>
            <td id="memberListLinks">
                @Html.ActionLink(item.FirstName, "UpdateMember/" + item.ID, "Portal")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberLevel1.MLevel)
            </td>
        </tr>
    }
</table>
<div>

    Page @(Model.PageNumber < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("ListMembers",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>

StarTech/IPGMMS/IPGMMS/Views/Portal/ListTests.cshtml
@{
    ViewBag.Title = "ListTests";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>ListTests</h2>
<p>Here we will list all the tests</p>

StarTech/IPGMMS/IPGMMS/Views/Portal/UpdateCertification.cshtml
@{
    ViewBag.Title = "UpdateCertification";
    Layout = "~/Views/Shared/_AdminPortalLayout.cshtml";
}

<h2>UpdateCertification</h2>
<p>Here we will allow an admin to edit the details of a certification including notes and what tests are associated with this certification.</p>